
import Nav from '@/components/nav'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
import { ClerkProvider } from '@clerk/nextjs'
import Particle from '@/components/Particle'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="pt">
    <head>
      <title>Be-Smart</title>
    </head>
      <body className={`${inter.className} font-primary overflow-x-hidden`}>
        <Nav/>
          <div>
           {/*<Particle/>*/}
              {children}
          </div>
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  )
}
